# Generated by Django 6.1 on 2026-09-20 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projects_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
