# Generated by Django 6.1 on 2026-09-22 19:34

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_projects_starred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('img_skill', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
